### ISSUE TITLE
hard to distinguish from tuple

### ISSUE THREAD

**Issue by brigadier** [egobrain/decimal#7]
It is hard to distinguish decimal from a tuple when the data can have different types. For example it can be value of some setting, and then we need to convert all settings (they can have values of different types) of the app to json. In this case having decimals as records or just as tuples with atom would help to match and choose different conversion routine.

**Comment by egobrain** [comment]
I don't want to add overhead to the decimal container, because it used in highload projects.
You may wrap decimal in additional tuple with a key manually or use [?is_decimal](https://github.com/egobrain/decimal/blob/master/include/decimal.hrl#L22) macro

**Comment by brigadier** [comment]
Indeed, it's about up to 10% slower. Forked it and changed to record here https://github.com/brigadier/decimal/
